# Generated by Django 2.0.7 on 2021-05-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
    ]
